// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_O9wNpXKD866dg6hLpGCS8PFIlkM4VIc',
    appId: '1:1017884773437:web:beaa0c49dbebdc60df6e54',
    messagingSenderId: '1017884773437',
    projectId: 'curan-app',
    authDomain: 'curan-app.firebaseapp.com',
    storageBucket: 'curan-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCjHHr_4RAbme8_6ru3MjAHulUtmh5y_A',
    appId: '1:1017884773437:android:263de9fbd08db0e3df6e54',
    messagingSenderId: '1017884773437',
    projectId: 'curan-app',
    storageBucket: 'curan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUk1TBiUdDXaY8EZncg5wQZ5DL2hQmtX8',
    appId: '1:1017884773437:ios:8749f2bea27d0185df6e54',
    messagingSenderId: '1017884773437',
    projectId: 'curan-app',
    storageBucket: 'curan-app.firebasestorage.app',
    iosBundleId: 'com.example.curan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUk1TBiUdDXaY8EZncg5wQZ5DL2hQmtX8',
    appId: '1:1017884773437:ios:8749f2bea27d0185df6e54',
    messagingSenderId: '1017884773437',
    projectId: 'curan-app',
    storageBucket: 'curan-app.firebasestorage.app',
    iosBundleId: 'com.example.curan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_O9wNpXKD866dg6hLpGCS8PFIlkM4VIc',
    appId: '1:1017884773437:web:9e577764e1d44ee1df6e54',
    messagingSenderId: '1017884773437',
    projectId: 'curan-app',
    authDomain: 'curan-app.firebaseapp.com',
    storageBucket: 'curan-app.firebasestorage.app',
  );
}
